export default {
  GET_TEAMS_REQUEST: '@teams/GET_TEAMS_REQUEST',
  GET_TEAMS_SUCCESS: '@teams/GET_TEAMS_SUCCESS',
  GET_TEAMS_FAILURE: '@teams/GET_TEAMS_FAILURE',
  SELECT_TEAM: '@teams/SELECT_TEAM',
  OPEN_TEAM_MODAL: '@teams/OPEN_TEAM_MODAL',
  CLOSE_TEAM_MODAL: '@teams/CLOSE_TEAM_MODAL',
  CREATE_TEAM_REQUEST: '@teams/CREATE_TEAM_REQUEST',
  CREATE_TEAM_SUCCESS: '@teams/CREATE_TEAM_SUCCESS',
  CREATE_TEAM_FAILURE: '@teams/CREATE_TEAM_FAILURE',
};
