export default {
  OPEN_MEMBERS_MODAL: '@members/OPEN_MEMBERS_MODAL',
  CLOSE_MEMBERS_MODAL: '@members/CLOSE_MEMBERS_MODAL',
  GET_MEMBERS_REQUEST: '@members/GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: '@members/GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILURE: '@members/GET_MEMBERS_FAILURE',
};
