export default {
  SIGN_UP_REQUEST: '@auth/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: '@auth/SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: '@auth/SIGN_UP_FAILURE',
  SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: '@auth/SIGN_IN_FAILURE',
  SIGN_OUT_REQUEST: '@auth/SIGN_OUT_REQUEST',
  GET_PERMISSIONS_SUCCESS: '@auth/GET_PERMISSIONS_SUCCESS',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
};
