export default {
  GET_PROJECTS_REQUEST: '@projects/GET_PROJECTS_REQUEST',
  GET_PROJECTS_SUCCESS: '@projects/GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAILURE: '@projects/GET_PROJECTS_FAILURE',
  OPEN_PROJECT_MODAL: '@teams/OPEN_PROJECT_MODAL',
  CLOSE_PROJECT_MODAL: '@teams/CLOSE_PROJECT_MODAL',
  CREATE_PROJECT_REQUEST: '@projects/CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: '@projects/CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: '@projects/CREATE_PROJECT_FAILURE',
};
